### ISSUE TITLE
Pytorch version of PGD attack

### ISSUE THREAD

**Issue by zaixizhang** [KaidiXu/GCN_ADV_Train#4]
Hello, I am quite interested in your work. Is there a pytorch version of PGDAttack on GCN?

**Comment by KaidiXu** [comment]
Hi,

I did see some PyTorch versions of this code such as: 
https://github.com/DSE-MSU/DeepRobust/blob/e6188b04fd8468b0d2349fac3c9f496755cff1e9/deeprobust/graph/global_attack/topology_attack.py

Hope it helps.

Kaidi

**Comment by zaixizhang** [comment]
Thanks!

Zaixi
